# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-09-08 14:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, unique=True)),
                ('teaser', models.CharField(max_length=500, unique=True)),
                ('description', models.CharField(blank=True, max_length=2000, unique=True)),
                ('slug', models.SlugField(unique=True)),
                ('order', models.IntegerField(default=0)),
                ('featured', models.BooleanField(default=True)),
            ],
        ),
    ]
