# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-09-08 14:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sarahjaine', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='subtitle',
            field=models.CharField(default='Message Board Application', max_length=50),
            preserve_default=False,
        ),
    ]
