# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-09-08 14:51
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sarahjaine', '0002_project_subtitle'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='project',
            options={'ordering': ['name']},
        ),
    ]
