# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-09-08 15:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sarahjaine', '0003_auto_20160908_1451'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='description',
            field=models.CharField(blank=True, max_length=2000),
        ),
    ]
