# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-09-08 17:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sarahjaine', '0005_auto_20160908_1521'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=b'project-images/'),
        ),
    ]
