# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-09-08 18:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sarahjaine', '0006_project_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='video',
            field=models.FileField(blank=True, null=True, upload_to=b'project-videos/'),
        ),
    ]
