# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-09-08 20:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sarahjaine', '0007_project_video'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='description',
            field=models.TextField(blank=True, max_length=2000),
        ),
    ]
