# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-09-08 21:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sarahjaine', '0008_auto_20160908_2013'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='image_detail',
            field=models.ImageField(blank=True, null=True, upload_to=b'project-images/'),
        ),
    ]
