# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-09-12 04:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sarahjaine', '0009_project_image_detail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='teaser',
            field=models.TextField(max_length=500, unique=True),
        ),
    ]
