# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-09-12 21:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sarahjaine', '0010_auto_20160912_0421'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='paragraph_1',
            field=models.TextField(blank=True, max_length=2000),
        ),
        migrations.AddField(
            model_name='project',
            name='paragraph_2',
            field=models.TextField(blank=True, max_length=2000),
        ),
        migrations.AddField(
            model_name='project',
            name='paragraph_3',
            field=models.TextField(blank=True, max_length=2000),
        ),
        migrations.AddField(
            model_name='project',
            name='subtitle_1',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='project',
            name='subtitle_2',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='project',
            name='subtitle_3',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
