# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-09-13 19:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sarahjaine', '0011_auto_20160912_2125'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='video_image',
            field=models.ImageField(blank=True, null=True, upload_to=b'project-videos/'),
        ),
    ]
