# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-09-16 19:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sarahjaine', '0012_project_video_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='project-images/'),
        ),
        migrations.AlterField(
            model_name='project',
            name='image_detail',
            field=models.ImageField(blank=True, null=True, upload_to='project-images/'),
        ),
        migrations.AlterField(
            model_name='project',
            name='video',
            field=models.FileField(blank=True, null=True, upload_to='project-videos/'),
        ),
        migrations.AlterField(
            model_name='project',
            name='video_image',
            field=models.ImageField(blank=True, null=True, upload_to='project-videos/'),
        ),
    ]
